// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyhwOsHEI1iRNsa5_Jv-ypDq6ofX7mYAA',
    appId: '1:397987935654:web:b063b147d36f544d238b67',
    messagingSenderId: '397987935654',
    projectId: 'news-proved',
    authDomain: 'news-proved.firebaseapp.com',
    storageBucket: 'news-proved.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt_YgwvtxJt7a4GxDF--_AqasvkUlYhIQ',
    appId: '1:397987935654:android:bdaf4be2be22475e238b67',
    messagingSenderId: '397987935654',
    projectId: 'news-proved',
    storageBucket: 'news-proved.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYVOhnkW-B5aERp_A_v9C182SvYuV36kc',
    appId: '1:397987935654:ios:f9f8e13174d39345238b67',
    messagingSenderId: '397987935654',
    projectId: 'news-proved',
    storageBucket: 'news-proved.appspot.com',
    iosBundleId: 'com.example.newsProved',
  );

}